### ISSUE TITLE
代码中路径问题

### ISSUE THREAD

**Issue by Xyzhao1999** [yhao-wang/2022-Summer-Internship#2]
# 问题
CascadeClassifier 使用了绝对路径且直接硬编码，对代码的移植不够友好

# 解决方案
1. 通过宏等方式来方便代码中修改
  1. 使用宏也可以通过路径拼接的方式来简化后续路径使用
2. 考虑通过参数传入的方式来进行

**Comment by yhao-wang** [comment]
两个问题全部收到！谢谢老师的指导，我今后一定注意，谢谢老师！
王禹淏
2022年7月5日




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Jul 5, 2022 02:19 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[yhao-wang/2022-Summer-Internship] 代码中路径问题 (Issue #2)

&nbsp;



 
问题
 
CascadeClassifier 使用了绝对路径且直接硬编码，对代码的移植不够友好
 
解决方案
  
通过宏等方式来方便代码中修改
 
使用宏也可以通过路径拼接的方式来简化后续路径使用
 
考虑通过参数传入的方式来进行

**Comment by Xyzhao1999** [comment]
代码中已经使用相对路径解决该问题了 后续也可以尝试下其他方案
